/*
 * This source file was generated by the Gradle 'init' task
 */
package pbo;

import java.util.List;

public class App {

    public String dosen = "Hans Yulian";

    // tambahkan kalian sendiri dengan format: NIM-NAMA
    // contoh: "1112048-Hans Yulian"
    public List<String> pesertaPBO = List.of(
    // "1112048-Hans Yulian"
            "1125025-Andhika Fatizaro Laoli",
            "1125013-Raymond Ferdinand",
            "1124013-Michelle Daniella",
     "1124004-David Christian Tanuonga",
    "1125044-Viktory Gabriel Kawulur",
    "1122037-Gregorius Jerriyana Putu Riken",
      "1125015-Clay Othniel Yonathan"
    );

    public void start() {
        System.out.println("Kelas PBO");
        System.out.println("Dosen: " + dosen);
        System.out.println("Peserta PBO Sejauh ini:");
        System.out.println("Total: " + pesertaPBO.size());
        for (int i = 0; i < pesertaPBO.size(); i++) {
            System.out.println(i + 1 + ". " + pesertaPBO.get(i));
        }
    }

    public static void main(String[] args) {
        new App().start();
    }
}
